"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { useState } from "react";
import Navbar from "./Navbar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const [darkMode, setDarkMode] = useState(false);
  console.log(darkMode);
  return (
    <html lang="en">
      <body
        className={`${poppins.className} ${
          darkMode ? "dark" : ""
        } w-full h-screen bg-[#fafbf5] max-w-[1200px] mx-auto px-9 pt-11`}
      >
        <Navbar darkMode={darkMode} setDarkMode={setDarkMode} />
        {children}
      </body>
    </html>
  );
}
